---
- name: create pfizer VM 
  hosts: localhost
  become: true
  var_files:
    - ./create-vm-vars.yml

  tasks:
  - name: "Create host pfizer-test1"
    redhat.satellite.host:
      username: "admin"
      password: "orange45"
      server_url: "https://olivia.homelab.com"
      name: { vm-name }
      hostgroup: toby-small-8.3-vm
      compute_resource: toby
      organization: aleberkn-lab
      location: basement
      operatingsystem: RedHat 8.3
      provision_method: image
      state: present
