--- 
- name: setup storageamdin user
  hosts: data1
  remote_user: ansible
  become: yes

  tasks:
    - name: ensure group storagegroup exists
      group:
        name: storagegroup
        state: present

    - name: create user “storageadmin” 
      user:
        name: storageadmin
        uid: 4000
        shell: /bin/bash 
        group: storagegroup 
        append: yes

    - name: sudo without password for wheel group 
      copy: 
        content: 'storageadmin ALL=(ALL:ALL) NOPASSWD:ALL' 
        dest: /etc/sudoers.d/wheel_nopasswd 
        mode: 0440

