---
- name: configure MOTD
  hosts: data1
  become: true
  vars:
    - system_owner: tobyalan@gmail.com
  tasks:
    - name: configure /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
