--- 
- name: setup storage user
  hosts: [ storage ]
  become: true

  tasks:
    - name: ensure group storagegroup exists
      group:
        name: storagegroup
        state: present

    - name: create user “storageadmin” 
      user:
        name: storageadmin
        uid: 4000
        shell: /bin/bash 
        group: storagegroup 
        append: yes

    - name: sudo without password for wheel group 
      copy: 
        content: 'storageadmin ALL=(ALL:ALL) NOPASSWD:ALL' 
        dest: /etc/sudoers.d/storageadmin.sudo
        mode: 0440

