---
- name: /etc/hosts is up to date
  hosts: [ all ]
  gather_facts: yes
  become: true

  tasks:
    - name: Deploy /etc/hosts
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
